### ISSUE TITLE
After new user creation no email leads to 'undefined'

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#11]
See attached screenshot

This cannot be changed -> email of sub account user cannot be set.
![smn_account_user_undefined](https://user-images.githubusercontent.com/10755214/55280226-bf00b980-5322-11e9-9b3a-416c0db3ebb1.jpg)

**Comment by slklubaoding** [comment]
System allows registering an email only once; and such registered account is an admin. Admins can add subaccounts. Subaccount login page has no email option as subaccounts are added by username and password only. Therefore ‘undefined’ is displayed.

**Comment by plalx** [comment]
We understand why it displays undefined, but that's still a bug. The label should simply be hidden rather than displaying undefined if there is no associated email.

**Comment by TkTzLabs** [comment]
Yes ! Totally agree with **plalx**. **Undefined** is for me like **null** would be shown to user. It is unwanted behaviour and must be fixed !

**Comment by TkTzLabs** [comment]
Better maybe to show just username and no email at all ?

**Comment by TkTzLabs** [comment]
Verified in the new version:

- No undefined in the "email" field shown for ordinary user

see screenshot

![smn_user_email_fix](https://user-images.githubusercontent.com/10755214/55545427-756ef080-56cd-11e9-8bf3-77b5947e64a1.jpg)


Thank you WaltonChain team
