### ISSUE TITLE
user creation password validation rules

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#12]
Would be good to add some password validation verification check.

right now you can add user with password of one character. It would be best to have some complexity check to low complexity passwords.

**Comment by disy-yin** [comment]
Yes. Good idea.

**Comment by TkTzLabs** [comment]
Verified in the new version:

- during the admin user account creation
- during the regular user account creation

syntax is now : Password must be at least 8 characters, including a number, an uppercase letter, a lowercase letter and a special character

Thank you WaltonChain team
