### ISSUE TITLE
Unable to serve favicon.ico

### ISSUE THREAD

**Issue by plalx** [disy-yin/CrossChain#16]
`GET http://localhost/favicon.ico` returns `HTTP 500 - Internal Server Error`, with a body of `"There was a problem finding the keystore."`, where `GET http://127.0.0.1/favicon.ico` returns the same status code, but with a body of `{"code":-1,"msg":"Error: 请先登录"}`.

**Comment by TkTzLabs** [comment]
Favicon.ico is requested by browser I believe - so it is fine if not exist - but yes that response message is really really weird !!! Good catch !

**Comment by plalx** [comment]
Oh right, it seems that Chrome is guilty of requesting `favicon.ico`. I had not realized that before, probably because most servers would return `404` instead of `500`. Still, the server's response seems odd indeed (at least from `localhost`) -- translated the other one and it says "please log in first".

**Comment by slklubaoding** [comment]
Your feedback has been received and we are dealing with it
