### ISSUE TITLE
Potential security concerns

### ISSUE THREAD

**Issue by plalx** [disy-yin/CrossChain#19]
I have noticed that the username & email address is stored in a cookie. Furthermore, the website is served through HTTP instead of HTTPS. If everything is only ever accessible from `localhost` it may not be not as problematic, but you may want to consider moving towards HTTPS and avoid storing personal information in cookies.

**Comment by ko12ko** [comment]
Our SMN system advocates for autonomy and is not centralized. Each SMN builds its own system. If you feel that you need https, you can configure the certificate yourselves.
