### ISSUE TITLE
smn_web -> buttons in popup doesnt works

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#2]
In Modify the WTC node I am not able to click on Confirm button -> nothing happen.

Using Chrome Version 73.0.3683.86 (Official Build) (64-bit

**Comment by plalx** [comment]
Perhaps what's happening is similar to issue #14, where network calls are simply taking a very long time to return. Have you checked the dev console (F12 in Chrome to open).

**Comment by TkTzLabs** [comment]
Verified in the new version:

- Not reproducible again, closing

Thank you WaltonChain team
