### ISSUE TITLE
Password reset code is valid for 60 seconds only not 10 minutes

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#20]
Fill up email and click on Get Verification Code:

1. After clicking on Get Verification Code there is a pop up saying that code will arrive to your email address and it is valid for 10 minutes.

2. Text change from English to  重新获取(50) with a count down -> BTW it should stay in english when GUI is in english and vice versa

3. Code is invalidated after 60 seconds.

Please fix that up.

![smn_reset_password](https://user-images.githubusercontent.com/10755214/55293796-846a5000-53fa-11e9-8f8d-47a2b844fdc4.jpg)

**Comment by slklubaoding** [comment]
It simply limits you to sending captchas only once for 60 seconds, and the content of the captcha is valid for 10 minutes

**Comment by TkTzLabs** [comment]
Hello, okay then but could you please still investigate ? I tried and I was unable to continue with resetting password... but yes of-course maybe it was because I clicked too many time when writing down this issue :)

**Comment by TkTzLabs** [comment]
Okay just tested again. If the countdown running, you can click on it and you will receive another code. the last one is the valid one.

**Comment by TkTzLabs** [comment]
Verified in the new version:

- RESEND is now in english

Thank you WaltonChain team
