### ISSUE TITLE
The path /var/dockerMongodb/db is not shared from OS X and is not known to Docker

### ISSUE THREAD

**Issue by nikravi** [disy-yin/CrossChain#25]
Running this command

`docker run -d -v /var/dockerMongodb/db:/data/db --name mongo --env MONGO_INITDB_DATABASE=smn --env MONGO_NON_ROOT_USERNAME=username --env MONGO_NON_ROOT_PASSWORD=123456 --env MONGO_NON_ROOT_ROLE=dbAdmin baoding/smn_mongo`

fails with `The path /var/dockerMongodb/db
is not shared from OS X and is not known to Docker.`

**Comment by nikravi** [comment]
To fix this, I created a directory which I have non-sudo access to, and updated the command to run with it:

`
docker run -d -v /Users/myUser/work/mongodb/:/data/db --name mongo --env MONGO_INITDB_DATABASE=smn --env MONGO_NON_ROOT_USERNAME=username --env MONGO_NON_ROOT_PASSWORD=123456 --env MONGO_NON_ROOT_ROLE=dbAdmin baoding/smn_mongo
`

**Comment by TkTzLabs** [comment]
@nikravi  thank you -> It would be great to add it to the readme.md WDYT @disy-yin ?

**Comment by slklubaoding** [comment]
The path /var/dockerMongodb/db is an optional path that you can change to any path
