### ISSUE TITLE
Step 7 - no Execution Account in dropdown

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#27]
In the Step 7 there is not Execution Account in the dropdown.

Please see attached screenshot

![smn_configure_account](https://user-images.githubusercontent.com/10755214/55545086-bdd9de80-56cc-11e9-9ce4-86a29361c29c.jpg)

**Comment by slklubaoding** [comment]
You need to add a Keystore first, then an Execution Account will appear

**Comment by TkTzLabs** [comment]
You are right sorry.
