### ISSUE TITLE
Key-Store management and running endorsements

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#28]
If Key-store that was used for Execution Account of endorsement is removed, please also rollback endorsement configurations back to the defaults and make endorsment stop / Unconfigured.

OR

Throw an error to user during the key-store removing that there are some endorsement configured with Execution Account derivated from key-store and first must be stopped and then it will allows key-store to be removed

Please I might be wrong so feel free to correct me.

**Comment by slklubaoding** [comment]
We have processed it and the next version will not appear
