### ISSUE TITLE
Add user validation on input

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#30]
Admin is able to create user with empty username -> with space " "

User " " cannot log in. I believe this input should has also some validation on input

**Comment by plalx** [comment]
Input should most likely be trimmed in most contexts of front-end and back-end, except perhaps for passwords (not sure what's the general practice, does most services accept leading/trailing spaces in passwords?). 

It's quite rare that leading/trailing spaces are meaningful. `"   "` username should have evaluated the same as empty string `""` and be caught by mandatory validation.

**Comment by slklubaoding** [comment]
We have received your feedback and are dealing with it
