### ISSUE TITLE
Unecessary "Please log in" warning for initial login

### ISSUE THREAD

**Issue by plalx** [disy-yin/CrossChain#31]
This is minimal, but there's an unnecessary "Please log in" warning (toast message) for the initial login redirection.

**Comment by ko12ko** [comment]
According to system settings, logout is automatic after 30 minutes of inactivity. Please confirm if timeout caused the logout status error.

**Comment by plalx** [comment]
No, just open the SMN website while being logged out at http://localhost and when you get redirected to the login page it warns you to login, but that's unecessary. It's a small detail, but it's annoying.

**Comment by ko12ko** [comment]
Sorry,I try to do it what you described,but did''t find this problem.May be you can try it again???

**Comment by plalx** [comment]
![image](https://user-images.githubusercontent.com/903992/56003543-e5184900-5c94-11e9-9d12-4d930c078242.png)

Does it in both, Edge and Chrome.

**Comment by slklubaoding** [comment]
We have received your feedback and are dealing with it
