### ISSUE TITLE
Suggest a list of worker addresses

### ISSUE THREAD

**Issue by plalx** [disy-yin/CrossChain#33]
Given worker/SMN association is managed through the `PermissionManageContract`, arbitrary worker addresses can't be added. It would be better if the UI would fetch the list of associated worker addresses with the configured reference SMN (from a gwtc node) and then lets you associate a keystore with each discovered worker, instead of allowing you to import arbitrary keystores which won't work anyway given they aren't associated to a SMN.

**Comment by Angus23203** [comment]
Refering to @plalx question, at the moment the `PermissionManageContract` requires the team to add the workers to the SMNs. Will the live situation be different? I.e. will the SMNs be authorised to add their own workers so the above solution wouldn't be needed or will the setup always go through the team? Wouldn't this be very cumbersome?

**Comment by slklubaoding** [comment]
We have received your feedback and are dealing with it
