### ISSUE TITLE
Can find Logs under the log tab

### ISSUE THREAD

**Issue by Angus23203** [disy-yin/CrossChain#34]
I've let the first endorsement run for a while. 
I can the last 6 log entries underneath the endorsement itself. But when I look for the logs in the 'Log' tab i can't find any log

I receive the error 'This contract has no operation record'

**Comment by plalx** [comment]
I can observe the same behavior: I have performed many endorsements, but only one is showing under the logs tab.

![image](https://user-images.githubusercontent.com/903992/55767071-6f6a6e00-5a45-11e9-90c9-ac7bcfc78319.png)

![image](https://user-images.githubusercontent.com/903992/55767712-0b957480-5a48-11e9-84f6-90a06f3b6ad3.png)

**Comment by slklubaoding** [comment]
The system has two logs:
1. Instant transaction log appears below the endorsement contract. It updates when a transaction is complete. Maximum 6 events appear there. If the transaction log does not update, there are no new endorsement transactions initiated.
2. Contract operation log — locates on a separate page. Query result is operation log under a selected contract: endorsement start/endorsement finish.

**Comment by Angus23203** [comment]
Can confirm @plalx results

**Comment by slklubaoding** [comment]
We have received your feedback and are dealing with it
