### ISSUE TITLE
Can't change endorsement without an error

### ISSUE THREAD

**Issue by Angus23203** [disy-yin/CrossChain#35]
After I stopped 'running' the first endorsement I tried to configure the second one.
It immidiatly returns an error in the Log details: _'2019-04-09 0:03:44 tips:Error: Returned error: replacement transaction underpriced'._
I see this error both in the second endorsement under the Winery chain and als on the endorsement on the Test chain

**Comment by Angus23203** [comment]
This seemed to correct itself after 15 minutes. But I have no idea why

**Comment by slklubaoding** [comment]
Do you have two endorsements running on one worker? When stopping the first endorsement, the transaction may have already been sent to blockchain and has a ‘Pending’ status. When the same worker starts the second endorsement and sends a transaction, the nonce collision and the above error report can occur. Please wait till the transaction of the first endorsement is complete, then no errors will occur with transactions for the second endorsement.

**Comment by Angus23203** [comment]
I stopped the first endorsement and started the second. I received the error above a couple of times in about 15 minutes before it actually started.
I understand why it goes wrong but maybe change the error to something meaningful?

**Comment by plalx** [comment]
When the following occurs, does it require additionnal intervention or the situation will resolve itself automatically? If it requires intervention then it's not obvious since the contract appears as "RUNNING".

![image](https://user-images.githubusercontent.com/903992/55806480-4df19c80-5aae-11e9-8b83-780fe4cad029.png)

**Comment by Angus23203** [comment]
The Endorsement on the testchain receives the following error:
2019-04-10 8:09:51 tips:Error: Invalid JSON RPC response: ""
Is it running?

**Comment by TkTzLabs** [comment]
Hello @Angus23203  I am having the same 2019-04-10 10:38:43 tips:Error: Invalid JSON RPC response: ""

**Comment by Angus23203** [comment]
ill close this issue
