### ISSUE TITLE
Endorsement contract transaction failure resulted in endorsement earnings going back to 0

### ISSUE THREAD

**Issue by plalx** [disy-yin/CrossChain#37]
I don't know if that is expected to happen or not from time to time, but I've encountered the following error which seems to have caused the endorsement earnings to go back to 0 (had processed a few endorsements already).

`2019-04-08 19:02:09 tips:Error: Transaction has been reverted by the EVM: { "blockHash": "0x6b76869b4082b1c41e4bb7ef4fd53ee1415eed3bce3f867a4e834d6a30af43e9", "blockNumber": 34601, "contractAddress": null, "cumulativeGasUsed": 34777, "from": "0xa0130008b668866f3633d8fd8b9ede2bcce926d2", "gasUsed": 34777, "logs": [], "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x2e7df1d4c7efc3915c067a893f4be67ffa01e57c", "transactionHash": "0x93784349da45e0ae4fed0ceba069b5e5516f5314ec47ccc3107ed304ac833ab1", "transactionIndex": 0 }`

**Comment by slklubaoding** [comment]
SMN Count is limited for each endorsement task(cross-chain data transport). Sometime more SMN are trying to do the same endorsement task. Therefore, some SMN could not do the endorsement and does not get any reward.
