### ISSUE TITLE
test child chain disappeared from list

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#38]
After restart of gwtc test child chain disappeared from the left list completely.

There was only winery but 3 contracts -> see attached screenshot
![smn_first](https://user-images.githubusercontent.com/10755214/55814677-4e5e5780-5aef-11e9-8bcd-05b2aeec7a1a.jpg)

I have removed keystore and now there are only 2 contracts
![smn_second](https://user-images.githubusercontent.com/10755214/55814720-603ffa80-5aef-11e9-97e1-0d455abc9e3d.jpg)

**Comment by plalx** [comment]
Try log off/log in. Seems somewhat similar to #15.

**Comment by TkTzLabs** [comment]
Tried and no luck

**Comment by Angus23203** [comment]
Worst case try to delete your mongo database folder

**Comment by TkTzLabs** [comment]
Yep, i know. Bottom line is that it should not happend !

**Comment by slklubaoding** [comment]
We have received your feedback and are dealing with it

**Comment by AboldUSER** [comment]
I resolved this by deleting my docker session and starting over. The first session only had the winery childchain, while the second session had both winery and test.
