### ISSUE TITLE
endorsment is running but getting insufficient funds

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#39]
Hello,

what should I do next ?

![smn_endormsment](https://user-images.githubusercontent.com/10755214/55828777-79f03a80-5b0d-11e9-8f2a-9f04f692d03f.jpg)

**Comment by Angus23203** [comment]
Does your worker have any balance on it?

**Comment by plalx** [comment]
Your worker doesn't seem to have any funds. I sent some coins your way.

**Comment by disy-yin** [comment]
Yes. your worker need wtc!

**Comment by TkTzLabs** [comment]
Thanks @plalx . received. No I am having 2019-04-10 10:38:43 tips:Error: Invalid JSON RPC response: ""

**Comment by disy-yin** [comment]
" Invalid JSON RPC response"???
OK. Please create another issue topic. Thankyou.
@TkTzLabs

**Comment by disy-yin** [comment]
I will close the issue.
Thank you.
