### ISSUE TITLE
SMN_WEB crashed -> restarted dockers and second docker cannot start up

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#4]
There was a really suspicious behaviour of **SMN_WEB** so I stopped all dockers by docker stop {containerID}.

I have started first and try **docker container ls**, second and tried **docker container ls** but it seems it doesn't start up.

see attached screenshot
![smn_second_docker](https://user-images.githubusercontent.com/10755214/55274987-49272e80-52df-11e9-8124-4f1b51c8a16c.jpg)

**Comment by TkTzLabs** [comment]
During writing this issue also first docker crashed .. please see screenshot as well 
![smn_second_docker-additionalinfo](https://user-images.githubusercontent.com/10755214/55274999-8db2ca00-52df-11e9-8d7c-a1f38368b468.jpg)

**Comment by ko12ko** [comment]
@TkTzLabs Enter the command `docker logs 8f4138f7528f` to view the log.
