### ISSUE TITLE
Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#40]
Hello,

after my worker got funded by @plalx (thanks). I have received another message:
2019-04-10 10:44:02 tips:Error: Invalid JSON RPC response: ""

![smn_rpc](https://user-images.githubusercontent.com/10755214/55864915-af347100-5b7d-11e9-87d0-dfbddf9b950c.jpg)

**Comment by Angus23203** [comment]
I had the same message.
Is the childchain running?

**Comment by TkTzLabs** [comment]
I have checked all docker logs and there is nothing suspicious

**Comment by ko12ko** [comment]
I'm sorry,the childchain does't work.

**Comment by ko12ko** [comment]
I'm sorry,the childchain didn't at work.It's running now,you can try  it.

**Comment by ko12ko** [comment]
Sorry.The subchain IP address is belong to the local network. That is why can't connect it.

**Comment by TkTzLabs** [comment]
@ko12ko  so what should we do to fix it ?

**Comment by Angus23203** [comment]
We have to wait till the childchain is available from the outside. Current IP starts with 192.168...  so we have to wait till it changed

**Comment by plalx** [comment]
@ko12ko You may want to consider reporting "child chain node unreachable" rather than "Invalid JSON RPC Response", because if the host was unreachable there was no response while this makes it look like if the remote child chain host is misbehaving.
