### ISSUE TITLE
In endorsment details missing SMN: address

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#41]
Hello,

in the endorsment details there is missing SMN address. Please check screenshot

![smn_smn](https://user-images.githubusercontent.com/10755214/55867917-b6f71400-5b83-11e9-9ee6-97f27ab56fd6.jpg)

**Comment by ko12ko** [comment]
When an error message appears below, the log does not provide SMN address (or endorsement earnings). This information is provided after the next successful transaction is recorded.

**Comment by TkTzLabs** [comment]
OK so let me verify this after it will be solved and without errors recorded below.

**Comment by AboldUSER** [comment]
I also received this same issue, except with me it stated "Error: Key derivation failed". 
![smn address error]
(https://user-images.githubusercontent.com/2985057/56412295-a6b0fa00-6251-11e9-9ddb-a88c017f880b.jpg)
