### ISSUE TITLE
Addind subaccount -> wrong error message

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#5]
I have tried to add account that already exists. There was a pop up but saying something misleading like "User name available". Should be something like "User name already exists" or similiar. see screenshot
![smn_account_available](https://user-images.githubusercontent.com/10755214/55276155-7fb97500-52f0-11e9-87ed-b7c46d9bf3c7.jpg)

**Comment by plalx** [comment]
Also, from a user experience perspective I wouldn't show an error popup. You can probably just display the same unobtrusive message that already shows when clicking "Query" for an existing username.

**Comment by TkTzLabs** [comment]
Verified in the new version:

- Fixed

![smn_user_exists](https://user-images.githubusercontent.com/10755214/55545736-1eb5e680-56ce-11e9-9d9a-9135c03a3741.jpg)


Thank you WaltonChain team
