### ISSUE TITLE
Chain Child list filter by status -> Stopped

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#6]
In the Chain Child list there  are three tabs ALL, RUNNING and STOPPED.

In All tabs there are all chains in STOPPED status. When I switch to STOPPED tab there is not record at all even there are two chain in STOPPED status. See attached screenshot.

In screenshot you can see on the top content of the ALL tab and on the bottom content of the STOPPED tab

![smn_child_chain_list](https://user-images.githubusercontent.com/10755214/55276206-3d446800-52f1-11e9-99e1-fb821e8c227a.jpg)

**Comment by TkTzLabs** [comment]
There is the same condition for RUNNING and STOP :
`else if ("RUNNING" == e) {
                                        for (var n = [], a = 0; a < t.msg.length; a++) {
                                            var l = t.msg[a];
                                            l.config && 1 == l.config.isRunning && (l.state = l.config.isRunning, n.push(l))
                                        }
                                        i.industryList = n
                                    } else if ("STOP" == e) {
                                        for (var o = [], c = 0; c < t.msg.length; c++) {
                                            var A = t.msg[c];
                                            A.config && 0 == A.config.isRunning && (A.state = A.config.isRunning, o.push(A))
                                        }
                                        i.industryList = o
                                    }`

**Comment by plalx** [comment]
> There is the same condition for RUNNING and STOP :
It's not the same, it's checking that `A.config.isRunning` is falsy (`== 0`) before pushing (`o.push(A)`) for the `"STOP"` condition block. 

I can't debug right now because I have killed my installation by removing the admin account though, but if you set a breakpoint in there check what `o` contains at the end and add a watch on `A.config.isRunning`: it should be falsy for stopped contracts.

**Comment by slklubaoding** [comment]
‘Unconfigured’ transactions show in the ALL tab only.
When a transaction is configured and has a STOPPED status, is shows in the STOPPED tab. When a transaction is configured and has a RUNNING status, it shows in the RUNNING tab.

**Comment by plalx** [comment]
@slklubaoding I think it would still be more intuitive to list unconfigured (and therefore stopped) transactions in the STOPPED tab, unless you introduce an UNCONFIGURED tab to make the distinction clear.
