### ISSUE TITLE
Adding keystore failed and smn docker crashed

### ISSUE THREAD

**Issue by TkTzLabs** [disy-yin/CrossChain#8]
call createsKeystore -> POST => 200
call getKeystores -> GET -> **502 Bad Gateway**

In the body response content was :
An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
If you are the system administrator of this resource then you should check
the error log for details.
Faithfully yours, **nginx.**

In smn_web action was successful with popup saying positive action was done.

**Currently I cannot add any more keystore as SMN docker crashed !!!! it is no longer running after this action.**

![smn_keystore](https://user-images.githubusercontent.com/10755214/55276410-b8a71900-52f3-11e9-87ff-ca38894c948c.jpg)
`

**Comment by slklubaoding** [comment]
The possible reason for this is that Keystore file is incorrect. We have updated the version so users cannot add incorrect Keystores already. Let us know whether the issue reoccurs.Thank you for reporting this issue.

**Comment by TkTzLabs** [comment]
Hello, sure thing. When we can expect the next release ?

**Comment by TkTzLabs** [comment]
Verified in the new version:

- incorrect keystore cannot be imported

Thank you WaltonChain team
