### ISSUE TITLE
Step 8 - SMN doesn't correspond to the sender

### ISSUE THREAD

**Issue by BuggerSee** [disy-yin/CrossChain#9]
When i try to execute the endorsement transaction, i get an Error : `SMN doesn't correspond to the sender`

Smn configuration is the following: 
`WTC node: http://gwtc:6545`
`SMN Address: 0xd98868e1d3736070deaf01a666271df9858110e7`

**Comment by TkTzLabs** [comment]
Hello, just to confirm i was facing similar issue - I will investigate on it more later.

**Comment by plalx** [comment]
I had the same issue and managed to fix the problem (only for tran `blockEn_test`) using `http://27.102.128.188:6545` (took it from the screenshot) instead of `http://gwtc:6545`  instead of `gwtc`.

**Comment by plalx** [comment]
Well, I have logged out/in and the transaction name seems to have changed now, from "blockEn_test" to "BlockEndorsement_test". Using `http://27.102.128.188:6545` doesn't work anymore and I get the original error.

**Comment by Angus23203** [comment]
i get the same error on all available contracts

**Comment by just1-guy** [comment]
Same issue on all available transaction too. Also it appears that we must add a wallet keystore in order to have an execution account.

**Comment by BuggerSee** [comment]
Meanwhile i get the error : `Insufficient contract balance, failed to start transaction` when trying to 
execute the endorsement transaction

**Comment by Angus23203** [comment]
Is there an update to this problem? 
This is the main issue we come across and prevents us from proper testing.

**Comment by plalx** [comment]
This is because worker/execution addresses need to be linked to SMNs using a smart contract. See issue #33. The team sent an email linking to a Google form where you should specify your worker's address and configured reference SMN.

**Comment by Angus23203** [comment]
This works now. Atleast for the people who sent the filled out form to the team. Thank you!

Still my question at #33 stands. Would the team always have link the worker addresses to the SMN address?

**Comment by just1-guy** [comment]
I sent the form previously but it still doesn't for me.

**Comment by slklubaoding** [comment]
We have received your feedback and are dealing with it
